### PR TITLE
Implement sonarqube functionality with test coverage & ignore sonarcube folders

### PR DESCRIPTION
**Pull request by OhSoooLucky**

### CODE REVIEW

**Comment by JamieVangeysel** [comment]
You mean dis 
image
? 🤷🏼‍♀️🤔

**Comment by OhSoooLucky** [comment]
Sonarqube is a local variant to test code quality pre-committing to have a clean codebase instead of an extra 'patch' commit.

**Comment by OhSoooLucky** [comment]
Approve, dewit, dewit now!

**Comment by FlyingWraptor** [comment]
DEWIT @JamieVangeysel

**Review by JamieVangeysel — CHANGES_REQUESTED** [review]
exclude extra file in .npmignore

**Review by JamieVangeysel — APPROVED** [review]
LGTM

**Pull request merged**
